---
image: continuumio/miniconda3:latest

variables:
  PRODUCTION_BRANCH: PAGER-production
  PRE_RELEASE_BRANCH: PAGER-dev
  REGISTER: localhost

before_script:
  - cd /builds/pager-wp8/data_management/
  - bash install.sh
  #- pip install -r requirements.txt
  #- python setup.py install
  #- python setup.py develop

stages:
  - unit-tests
  - integration-tests
  - test-build
  - deployment

unittest:
  stage: unit-tests
  tags:
    - Deployment
  script:
    - cd /builds/pager-wp8/data_management/tests/unittests
    - echo "Running unittests for data_management"
    - pytest .
  #rules:
  #  - if: $CI_COMMIT_BRANCH == $PRE_RELEASE_BRANCH


