---
image: continuumio/miniconda3:latest

variables:
  PRODUCTION_BRANCH: PAGER-production
  PRE_RELEASE_BRANCH: PAGER-alpha
  DEVELOPMENT_BRANCH: PAGER-dev
  REGISTER: localhost
  TEST_BRANCH: tests
  GEOML_BRANCH: sync_with_GeoML

before_script:
  - eval "$(conda shell.bash hook)"
  - conda create -n deploy python=3.11
  - cd /builds/pager-wp8/data_management/
  - bash install.sh -e deploy

stages:
  - unit-tests
  - integration-tests
  - test-build
  - deployment

unittest:
  stage: unit-tests
  tags:
    - testing
  script:
    - cd /builds/pager-wp8/data_management/
    - echo "Running unittests for data_management"
    - conda activate deploy
    - python -m pytest -s tests/io/
  rules:
    - if: ($CI_COMMIT_BRANCH == $TEST_BRANCH || $CI_COMMIT_BRANCH == $TEST_BRANCH || $CI_COMMIT_BRANCH == $TEST_BRANCH || $CI_COMMIT_BRANCH == $GEOML_BRANCH)
#integrationtest:
#  stage: integration-tests
#  tags:
#    - Deployment
#  script:
#    - cd /builds/pager-wp8/data_management/tests/integration_tests
#    - echo "Running integration for data_management"
#    - pytest .
#  rules:
#    - if: ($CI_COMMIT_BRANCH == $PRE_RELEASE_BRANCH || $CI_COMMIT_BRANCH == $DEVELOPMENT_BRANCH || $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH)

#testbuild:
#  stage: test-build
#  tags:
#    - Deployment
#  script:
#    - cd /builds/pager-wp8/data_management/docker
#    - echo "Running docker image test build for data_management"
#    - bash build_
#  rules:
#    - if: ($CI_COMMIT_BRANCH == $PRE_RELEASE_BRANCH || $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH)

