line-length = 120
lint.select = ["ALL"]
lint.ignore = ["G004", "ANN001", "I001" "D211", "D103","S101", "D202", "D200", "D212", "C901", "ANN201", "ANN204", "D107", "D101", "EM102", "TRY003", "F541", "COM812", "D203", "ISC001"] # allowing f-strings in logging statements
