apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-management-check-routines
spec:
  selector:
    matchLabels:
      app: data-management-check-routines
  replicas: 1
  template:
    metadata:
      labels:
        app: data-management-check-routines
    spec:
      containers:
      - name: data-management-plotting-routines
        image: kub1:5000/data-management:latest
        command: ["./check_entrypoint.sh"]
        env:
          - name: RECURRENT
            value: "1"
          - name: LOG_DIR
            value: "/PAGER/WP8/logs/"
          - name: NOTIFY
            value: "0"
        volumeMounts:
           - name: host-volume
             mountPath: /PAGER
        ports:
        - containerPort: 80
      volumes:
        - name: host-volume
          hostPath:
            path: /home/ruggero/PAGER
            type: Directory
