name: Build Sphinx PDF

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended
          pip install -r requirements.txt

      - name: Build Sphinx PDF
        env:
          SWVO_CHANGELOG_TOKEN: ${{ secrets.SWVO_CHANGELOG_TOKEN }}
        run: |
          cd docs
          make latexpdf

      - name: Upload PDF Docs
        uses: actions/upload-artifact@v4
        with:
          name: pdf-docs
          path: docs/_build/latex/swvo.pdf

      - name: Push PDF to docs branch
        run: |
          git fetch
          git checkout -B docs
          git config user.name "GitHub Actions (by ${GITHUB_ACTOR})"
          git config user.email "actions@github.com"
          rm -f *.pdf
          cp docs/_build/latex/swvo.pdf ./swvo.pdf
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          git add swvo.pdf
          git commit -m "Update PDF docs from GitHub Actions (commit ${SHORT_SHA} by ${GITHUB_ACTOR})" || echo "No changes to commit"
          git push docs
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
