name: Build Sphinx HTML

on:
  push:
    branches: ["PAGER-prod"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Sphinx HTML
        run: |
          cd docs
          make html

      - name: Upload HTML Docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/

      - name: Deploy to GitLab Pages Repo
        run: |

      # - name: Deploy to GitLab Pages Repo
      #   run: |
      #     git clone https://${GL_USERNAME}:${GL_TOKEN}@git.gfz-potsdam.de/jhawar/github_docs.git repo
      #     cd repo
      #     git config user.name "GitHub Actions (via ${GITHUB_ACTOR})"
      #     git config user.email "actions@github.com"
      #     cp -r ../docs/_build/html ./docs
      #     git add docs
      #     git commit -m "Update docs from GitHub Actions" || echo "No changes to commit"
      #     git push origin main
      #   env:
      #     GL_USERNAME: ${{ secrets.GL_USERNAME }}
      #     GL_TOKEN: ${{ secrets.GL_TOKEN }}
      #     GITHUB_ACTOR: ${{ github.actor }}
