name: SWVO CI

on:
  push:
    branches:
      - PAGER-prod
      - tests
  pull_request:
    branches:
      - PAGER-prod
      - tests
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest . tests/io/
